; Photo Studio ReShade preset "Cinematic warm" - made for Blue Protocol: Star Resonance.
; Warmer light, a gentle contrast curve, a little more color and a soft vignette. Needs SweetFX and prod80.
; License: AGPL-3.0-or-later - https://github.com/StellarProtocol/StellarPhotoStudioPlugin
Techniques=prod80_04_ColorTemperature@PD80_04_Color_Temperature.fx,Curves@Curves.fx,Vibrance@Vibrance.fx,Vignette@Vignette.fx
TechniqueSorting=prod80_04_ColorTemperature@PD80_04_Color_Temperature.fx,Curves@Curves.fx,Vibrance@Vibrance.fx,Vignette@Vignette.fx

[Curves.fx]
Contrast=0.150000
Formula=4
Mode=0

[PD80_04_Color_Temperature.fx]
Kelvin=5400
LumPreservation=1.000000
kMix=0.400000

[Vibrance.fx]
Vibrance=0.100000
VibranceRGBBalance=1.000000,1.000000,1.000000

[Vignette.fx]
Amount=-0.300000
Center=0.500000,0.500000
Radius=1.600000
Ratio=1.000000
Slope=2
Type=0
