; Photo Studio ReShade preset "Dreamy glow" - made for Blue Protocol: Star Resonance.
; A soft glow around lights and bright areas, with a wide, gentle haze of light from the brightest spots. Needs FXShaders.
; License: AGPL-3.0-or-later - https://github.com/StellarProtocol/StellarPhotoStudioPlugin
Techniques=ArcaneBloom@ArcaneBloom.fx,MagicHDR@MagicHDR.fx
TechniqueSorting=ArcaneBloom@ArcaneBloom.fx,MagicHDR@MagicHDR.fx

[ArcaneBloom.fx]
uAdapt_Intensity=0.000000
uBloomIntensity=0.500000
uMaxBrightness=50.000000

[MagicHDR.fx]
BlendingAmount=0.500000
BlendingBase=0.800000
BloomAmount=0.200000
BloomBrightness=2.000000
BloomSaturation=1.000000
BlurSize=0.500000
Exposure=0.000000
InputExposure=0.000000
InvTonemap=0
Tonemap=0
