; Photo Studio ReShade preset "Dreamy glow" - made for Blue Protocol: Star Resonance.
; A soft, warm glow around lights and bright areas, with a wide, gentle haze of light from the brightest spots. Needs FXShaders.
; License: AGPL-3.0-or-later - https://github.com/StellarProtocol/StellarPhotoStudioPlugin
Techniques=NeoBloom@NeoBloom.fx,MagicHDR@MagicHDR.fx
TechniqueSorting=NeoBloom@NeoBloom.fx,MagicHDR@MagicHDR.fx

[MagicHDR.fx]
BlendingAmount=0.500000
BlendingBase=0.800000
BloomAmount=0.200000
BloomBrightness=2.000000
BloomSaturation=1.000000
BlurSize=0.500000
Exposure=0.000000
InputExposure=0.000000
InvTonemap=0
Tonemap=0

[NeoBloom.fx]
BloomBlendMode=1
ColorFilter=1.000000,0.960000,0.920000
Intensity=0.500000
MagicMode=0
MaxBrightness=50.000000
Mean=1.000000
NormalizeBrightness=1
Saturation=1.200000
Variance=3.000000
