; Photo Studio ReShade preset "Lens flare" - made for Blue Protocol: Star Resonance.
; Soft hexagonal lens flares from the brightest lights, framed by a gentle dark vignette. Needs FXShaders.
; License: AGPL-3.0-or-later - https://github.com/StellarProtocol/StellarPhotoStudioPlugin
Techniques=HexLensFlare@HexLensFlare.fx,ArtisticVignette@ArtisticVignette.fx
TechniqueSorting=HexLensFlare@HexLensFlare.fx,ArtisticVignette@ArtisticVignette.fx

[ArtisticVignette.fx]
BlendMode=0
VignetteColor=0.000000,0.000000,0.000000,0.450000
VignetteRatio=0.000000
VignetteShape=1
VignetteStartEnd=0.550000,1.500000

[HexLensFlare.fx]
uColor0=1.000000,0.820000,0.550000
uColor1=0.450000,0.650000,1.000000
uColor2=1.000000,0.600000,0.300000
uColor3=0.550000,0.900000,1.000000
uIntensity=0.500000
uScale=1.000000
uThreshold=0.970000
