; Photo Studio ReShade preset "Subject focus" - made for Blue Protocol: Star Resonance.
; Keeps what is close to the camera in full color and dims and desaturates the distance behind it. Uses depth, so it only shows in photos with the Screen shape. Needs OtisFX.
; License: AGPL-3.0-or-later - https://github.com/StellarProtocol/StellarPhotoStudioPlugin
Techniques=Emphasize@Emphasize.fx
TechniqueSorting=Emphasize@Emphasize.fx

[Emphasize.fx]
BlendColor=0.000000,0.000000,0.000000
BlendFactor=0.350000
EffectFactor=0.550000
FocusDepth=0.000000
FocusEdgeDepth=0.250000
FocusRangeDepth=0.050000
Spherical=0
